
class lu_mstr_md:

    def lu_object_type(self):
        return [
            {'PA_OBJ_TYPE_ID': '6', 'PA_OBJ_TYPE_DESC': 'Custom Group', 'MD_OBJ_TYPE_ID': '1',
             'MD_OBJ_TYPE_BEZ': 'Filter'},
            {'PA_OBJ_TYPE_ID': '8', 'PA_OBJ_TYPE_DESC': 'Data Import Cube', 'MD_OBJ_TYPE_ID': '3',
             'MD_OBJ_TYPE_BEZ': 'Report'},
            {'PA_OBJ_TYPE_ID': '16', 'PA_OBJ_TYPE_DESC': 'Filter', 'MD_OBJ_TYPE_ID': '1', 'MD_OBJ_TYPE_BEZ': 'Filter'},
            {'PA_OBJ_TYPE_ID': '40', 'PA_OBJ_TYPE_DESC': 'Template', 'MD_OBJ_TYPE_ID': '2',
             'MD_OBJ_TYPE_BEZ': 'Template'},
            {'PA_OBJ_TYPE_ID': '31', 'PA_OBJ_TYPE_DESC': 'SQL Report', 'MD_OBJ_TYPE_ID': '3',
             'MD_OBJ_TYPE_BEZ': 'Report'},
            {'PA_OBJ_TYPE_ID': '19', 'PA_OBJ_TYPE_DESC': 'SQL Report', 'MD_OBJ_TYPE_ID': '3',
             'MD_OBJ_TYPE_BEZ': 'Report'},
            {'PA_OBJ_TYPE_ID': '23', 'PA_OBJ_TYPE_DESC': 'Metric', 'MD_OBJ_TYPE_ID': '4', 'MD_OBJ_TYPE_BEZ': 'Metric'},
            {'PA_OBJ_TYPE_ID': '107', 'PA_OBJ_TYPE_DESC': 'User Folder', 'MD_OBJ_TYPE_ID': '8',
             'MD_OBJ_TYPE_BEZ': 'Folder'},
            {'PA_OBJ_TYPE_ID': '2', 'PA_OBJ_TYPE_DESC': 'Attribute Element Prompt', 'MD_OBJ_TYPE_ID': '10',
             'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '37', 'PA_OBJ_TYPE_DESC': 'Embedded Prompt', 'MD_OBJ_TYPE_ID': '10',
             'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '58', 'PA_OBJ_TYPE_DESC': 'Level prompt', 'MD_OBJ_TYPE_ID': '10',
             'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '24', 'PA_OBJ_TYPE_DESC': 'Object Prompt', 'MD_OBJ_TYPE_ID': '10',
             'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '28', 'PA_OBJ_TYPE_DESC': 'Prompt', 'MD_OBJ_TYPE_ID': '10', 'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '57', 'PA_OBJ_TYPE_DESC': 'Prompt Expression Draft', 'MD_OBJ_TYPE_ID': '10',
             'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '36', 'PA_OBJ_TYPE_DESC': 'Value Prompt', 'MD_OBJ_TYPE_ID': '10',
             'MD_OBJ_TYPE_BEZ': 'Prompt'},
            {'PA_OBJ_TYPE_ID': '1', 'PA_OBJ_TYPE_DESC': 'Attribute', 'MD_OBJ_TYPE_ID': '12',
             'MD_OBJ_TYPE_BEZ': 'Attribute'},
            {'PA_OBJ_TYPE_ID': '15', 'PA_OBJ_TYPE_DESC': 'Fact', 'MD_OBJ_TYPE_ID': '13', 'MD_OBJ_TYPE_BEZ': 'Fact'},
            {'PA_OBJ_TYPE_ID': '102', 'PA_OBJ_TYPE_DESC': 'System Hierarchy', 'MD_OBJ_TYPE_ID': '14',
             'MD_OBJ_TYPE_BEZ': 'Dimension'},
            {'PA_OBJ_TYPE_ID': '103', 'PA_OBJ_TYPE_DESC': 'User Hierarchy', 'MD_OBJ_TYPE_ID': '14',
             'MD_OBJ_TYPE_BEZ': 'Dimension'},
            {'PA_OBJ_TYPE_ID': '35', 'PA_OBJ_TYPE_DESC': 'Transformation', 'MD_OBJ_TYPE_ID': '43',
             'MD_OBJ_TYPE_BEZ': 'Role'},
            {'PA_OBJ_TYPE_ID': '5', 'PA_OBJ_TYPE_DESC': 'Consolidation', 'MD_OBJ_TYPE_ID': '47',
             'MD_OBJ_TYPE_BEZ': 'Consolidation'},
            {'PA_OBJ_TYPE_ID': '7', 'PA_OBJ_TYPE_DESC': 'Document', 'MD_OBJ_TYPE_ID': '55',
             'MD_OBJ_TYPE_BEZ': 'DocumentDefinition'},
            {'PA_OBJ_TYPE_ID': '14', 'PA_OBJ_TYPE_DESC': 'Dossier', 'MD_OBJ_TYPE_ID': '55',
             'MD_OBJ_TYPE_BEZ': 'DocumentDefinition'},
            {'PA_OBJ_TYPE_ID': '110', 'PA_OBJ_TYPE_DESC': 'Security Filter', 'MD_OBJ_TYPE_ID': '58',
             'MD_OBJ_TYPE_BEZ': 'Security Filter'},
            {'PA_OBJ_TYPE_ID': '-1', 'PA_OBJ_TYPE_DESC': 'Search', 'MD_OBJ_TYPE_ID': '39', 'MD_OBJ_TYPE_BEZ': 'Search'},
            {'PA_OBJ_TYPE_ID': '-2', 'PA_OBJ_TYPE_DESC': 'Shortcut', 'MD_OBJ_TYPE_ID': '18',
             'MD_OBJ_TYPE_BEZ': 'Shortcut'},
        ]