
class lu_mstr_md:

    def lu_object_type(self):
        return [
            {'OBJECT_TYPE_ID': '1', 'OBJECT_TYPE_BEZ': 'Filter', 'CONSTANT': 'DssTypeFilter',
             'DESCRIPTION': 'A restriction on the data in the warehouse (Filters)'},
            {'OBJECT_TYPE_ID': '2', 'OBJECT_TYPE_BEZ': 'Template', 'CONSTANT': 'DssTypeTemplate',
             'DESCRIPTION': 'The layout of a report (Templates)'},
            {'OBJECT_TYPE_ID': '3', 'OBJECT_TYPE_BEZ': 'Report', 'CONSTANT': 'DssTypeReportDefinition',
             'DESCRIPTION': 'Describes a report that can be executed (Reports)'},
            {'OBJECT_TYPE_ID': '4', 'OBJECT_TYPE_BEZ': 'Metric', 'CONSTANT': 'DssTypeMetric',
             'DESCRIPTION': 'A formula to be evaluated at a specific dimensionality (Metrics)'},
            {'OBJECT_TYPE_ID': '6', 'OBJECT_TYPE_BEZ': 'Autostyle', 'CONSTANT': 'DssTypeAutostyles',
             'DESCRIPTION': 'A custom or predefined formatted layout for a report (Autostyle)'},
            {'OBJECT_TYPE_ID': '8', 'OBJECT_TYPE_BEZ': 'Folder', 'CONSTANT': 'DssTypeFolder',
             'DESCRIPTION': 'A collection of objects (Folders)'},
            {'OBJECT_TYPE_ID': '10', 'OBJECT_TYPE_BEZ': 'Prompt', 'CONSTANT': 'DssTypePrompt',
             'DESCRIPTION': 'A method to prompt the user for information (Prompts)'},
            {'OBJECT_TYPE_ID': '11', 'OBJECT_TYPE_BEZ': 'Function', 'CONSTANT': 'DssTypeFunction',
             'DESCRIPTION': 'A function that can be used to build expressions (Functions)'},
            {'OBJECT_TYPE_ID': '12', 'OBJECT_TYPE_BEZ': 'Attribute', 'CONSTANT': 'DssTypeAttribute',
             'DESCRIPTION': 'A natural grouping of data (Attributes)'},
            {'OBJECT_TYPE_ID': '13', 'OBJECT_TYPE_BEZ': 'Fact', 'CONSTANT': 'DssTypeFact',
             'DESCRIPTION': 'A value that can be read directly from the warehouse (Facts)'},
            {'OBJECT_TYPE_ID': '14', 'OBJECT_TYPE_BEZ': 'Dimension', 'CONSTANT': 'DssTypeDimension',
             'DESCRIPTION': 'A grouping of related attributes (Hierarchies)'},
            {'OBJECT_TYPE_ID': '15', 'OBJECT_TYPE_BEZ': 'Table', 'CONSTANT': 'DssTypeTable',
             'DESCRIPTION': 'A logical table (Logical Table)'},
            {'OBJECT_TYPE_ID': '18', 'OBJECT_TYPE_BEZ': 'Shortcut', 'CONSTANT': 'DssTypeShortcut',
             'DESCRIPTION': 'Contains a reference to another DSS Object (Shortcuts)'},
            {'OBJECT_TYPE_ID': '23', 'OBJECT_TYPE_BEZ': 'Find', 'CONSTANT': 'DssTypeFindObject',
             'DESCRIPTION': '(Deprecated) Describes a simple search (Search definition)'},
            {'OBJECT_TYPE_ID': '34', 'OBJECT_TYPE_BEZ': 'User', 'CONSTANT': 'DssTypeUser',
             'DESCRIPTION': 'Represents a user or group of users of the system (Groups / Users)'},
            {'OBJECT_TYPE_ID': '43', 'OBJECT_TYPE_BEZ': 'Role', 'CONSTANT': 'DssTypeRole',
             'DESCRIPTION': 'Placeholder to describe way of extending an attribute (Transformations)'},
            {'OBJECT_TYPE_ID': '47', 'OBJECT_TYPE_BEZ': 'Consolidation', 'CONSTANT': 'DssTypeConsolidation',
             'DESCRIPTION': 'Collection of consolidation elements (Consolidations)'},
            {'OBJECT_TYPE_ID': '56', 'OBJECT_TYPE_BEZ': 'DrillMap', 'CONSTANT': 'DssTypeDrillMap',
             'DESCRIPTION': 'Describes a set of possible drill paths (Drill Maps)'},
            {'OBJECT_TYPE_ID': '58', 'OBJECT_TYPE_BEZ': 'Security Filter', 'CONSTANT': 'DssTypeMDSecurityFilter',
             'DESCRIPTION': 'Holds filter restrictions that can be applied to a user (Security Filters)'},
            {'OBJECT_TYPE_ID': '-1', 'OBJECT_TYPE_BEZ': 'Unkwon', 'CONSTANT': 'DssTypeUnknown',
             'DESCRIPTION': 'Type of object is not specified'},
            {'OBJECT_TYPE_ID': '0', 'OBJECT_TYPE_BEZ': 'Reserved', 'CONSTANT': 'DssTypeReserved',
             'DESCRIPTION': 'Never used, and all functions should check that zero(0) never pass for a type.'},
            {'OBJECT_TYPE_ID': '5', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '7', 'OBJECT_TYPE_BEZ': 'Aggregation Metric', 'CONSTANT': 'DssTypeAggMetric',
             'DESCRIPTION': 'A formula to be evaluated at any dimensionality (Base Formulas)'},
            {'OBJECT_TYPE_ID': '9', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '16', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '17', 'OBJECT_TYPE_BEZ': 'Factgroup', 'CONSTANT': 'DssTypeFactGroup',
             'DESCRIPTION': 'A collection of related facts (Fact groups)'},
            {'OBJECT_TYPE_ID': '19', 'OBJECT_TYPE_BEZ': 'Resolution', 'CONSTANT': 'DssTypeResolution',
             'DESCRIPTION': 'A collection of answers to prompts (Prompt answers)'},
            {'OBJECT_TYPE_ID': '20', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '21', 'OBJECT_TYPE_BEZ': 'AttributeForm', 'CONSTANT': 'DssTypeAttributeForm',
             'DESCRIPTION': 'Represents a value on elements of an attribute (Attribute forms)'},
            {'OBJECT_TYPE_ID': '22', 'OBJECT_TYPE_BEZ': 'Schema', 'CONSTANT': 'DssTypeSchema',
             'DESCRIPTION': 'Collection of objects that define the warehouse structure (Schema)'},
            {'OBJECT_TYPE_ID': '24', 'OBJECT_TYPE_BEZ': 'Type Catalog', 'CONSTANT': 'DssTypeCatalog',
             'DESCRIPTION': 'List of (relevant) tables in a database (Catalogs)'},
            {'OBJECT_TYPE_ID': '25', 'OBJECT_TYPE_BEZ': 'CatalogDefn', 'CONSTANT': 'DssTypeCatalogDefn',
             'DESCRIPTION': 'Describes how to construct a catalog (Catalog definitions)'},
            {'OBJECT_TYPE_ID': '26', 'OBJECT_TYPE_BEZ': 'Column', 'CONSTANT': 'DssTypeColumn',
             'DESCRIPTION': 'The properties needed to define a column of a DB table (Columns)'},
            {'OBJECT_TYPE_ID': '27', 'OBJECT_TYPE_BEZ': 'PropertyGroup', 'CONSTANT': 'DssTypePropertyGroup',
             'DESCRIPTION': 'Used to cache lists of property sets (Internal Object)'},
            {'OBJECT_TYPE_ID': '28', 'OBJECT_TYPE_BEZ': 'PropertySet', 'CONSTANT': 'DssTypePropertySet',
             'DESCRIPTION': 'Holds the definition of a property set (Properties)'},
            {'OBJECT_TYPE_ID': '29', 'OBJECT_TYPE_BEZ': 'DBRole', 'CONSTANT': 'DssTypeDBRole',
             'DESCRIPTION': 'Represents a logical database (Database Instance)'},
            {'OBJECT_TYPE_ID': '30', 'OBJECT_TYPE_BEZ': 'DBLogin', 'CONSTANT': 'DssTypeDBLogin',
             'DESCRIPTION': 'Describes how to login to a database (Database Login)'},
            {'OBJECT_TYPE_ID': '31', 'OBJECT_TYPE_BEZ': 'DBConnection', 'CONSTANT': 'DssTypeDBConnection',
             'DESCRIPTION': 'Describes how to connect to a database (Database Connection)'},
            {'OBJECT_TYPE_ID': '32', 'OBJECT_TYPE_BEZ': 'Project', 'CONSTANT': 'DssTypeProject',
             'DESCRIPTION': 'A environment in which to perform OLAP analysis (Projects)'},
            {'OBJECT_TYPE_ID': '33', 'OBJECT_TYPE_BEZ': 'ServerDef', 'CONSTANT': 'DssTypeServerDef',
             'DESCRIPTION': 'A description of a configuration of a DSS Server (Server Definitions)'},
            {'OBJECT_TYPE_ID': '35', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '36', 'OBJECT_TYPE_BEZ': 'Configuration', 'CONSTANT': 'DssTypeConfiguration',
             'DESCRIPTION': 'Top level object - represents a Castor installation (Castor Server Config.)'},
            {'OBJECT_TYPE_ID': '37', 'OBJECT_TYPE_BEZ': 'Request', 'CONSTANT': 'DssTypeRequest',
             'DESCRIPTION': 'Describes a DSS Server request (Scheduled requests)'},
            {'OBJECT_TYPE_ID': '38', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '39', 'OBJECT_TYPE_BEZ': 'Search', 'CONSTANT': 'DssTypeSearch',
             'DESCRIPTION': 'Describes criteria that specify a search for objects (Searches)'},
            {'OBJECT_TYPE_ID': '40', 'OBJECT_TYPE_BEZ': 'SearchFolder', 'CONSTANT': 'DssTypeSearchFolder',
             'DESCRIPTION': 'Folder-like object used to store result of a search (Search Folders)'},
            {'OBJECT_TYPE_ID': '41', 'OBJECT_TYPE_BEZ': 'Unused', 'CONSTANT': 'Unused', 'DESCRIPTION': 'None'},
            {'OBJECT_TYPE_ID': '42', 'OBJECT_TYPE_BEZ': 'FunctionPackageDefinition',
             'CONSTANT': 'DssTypeFunctionPackageDefinition',
             'DESCRIPTION': 'Describes a package of functions (Functions Definitions)'},
            {'OBJECT_TYPE_ID': '44', 'OBJECT_TYPE_BEZ': 'SecurityRole', 'CONSTANT': 'DssTypeSecurityRole',
             'DESCRIPTION': 'Holds privileges of a user that plays a certain role (Security Roles)'},
            {'OBJECT_TYPE_ID': '45', 'OBJECT_TYPE_BEZ': 'InBox', 'CONSTANT': 'DssTypeInBox',
             'DESCRIPTION': 'Shortcut to a folder (Shortcuts to folders)'},
            {'OBJECT_TYPE_ID': '46', 'OBJECT_TYPE_BEZ': 'InBoxMsg', 'CONSTANT': 'DssTypeInBoxMsg',
             'DESCRIPTION': 'Describes an uncollected report on a DSS Server (DSS Server Reports)'},
            {'OBJECT_TYPE_ID': '48', 'OBJECT_TYPE_BEZ': 'ConsolidationElement',
             'CONSTANT': 'DssTypeConsolidationElement',
             'DESCRIPTION': 'Arithmetic expression over elements (Consolidation elements)'},
            {'OBJECT_TYPE_ID': '49', 'OBJECT_TYPE_BEZ': 'ScheduleEvent', 'CONSTANT': 'DssTypeScheduleEvent',
             'DESCRIPTION': 'An event that can trigger a scheduled report (Scheduled events)'},
            {'OBJECT_TYPE_ID': '50', 'OBJECT_TYPE_BEZ': 'ScheduleObject', 'CONSTANT': 'DssTypeScheduleObject',
             'DESCRIPTION': 'Something that can be triggered (Scheduled objects)'},
            {'OBJECT_TYPE_ID': '51', 'OBJECT_TYPE_BEZ': 'ScheduleTrigger', 'CONSTANT': 'DssTypeScheduleTrigger',
             'DESCRIPTION': 'Binding between schedule event and object (Scheduled triggers)'},
            {'OBJECT_TYPE_ID': '52', 'OBJECT_TYPE_BEZ': 'Link', 'CONSTANT': 'DssTypeLink',
             'DESCRIPTION': 'Holder of a property that spans objects (Links)'},
            {'OBJECT_TYPE_ID': '53', 'OBJECT_TYPE_BEZ': 'DBTable', 'CONSTANT': 'DssTypeDBTable',
             'DESCRIPTION': 'A physical table in a database (Physical tables)'},
            {'OBJECT_TYPE_ID': '54', 'OBJECT_TYPE_BEZ': 'TableSource', 'CONSTANT': 'DssTypeTableSource',
             'DESCRIPTION': 'Physical tables with same suffix and prefix (Same suffix and prefix tables)'},
            {'OBJECT_TYPE_ID': '55', 'OBJECT_TYPE_BEZ': 'DocumentDefinition', 'CONSTANT': 'DssTypeDocumentDefinition',
             'DESCRIPTION': 'An document built from reports and HTML text (Report Services Documents)'},
            {'OBJECT_TYPE_ID': '57', 'OBJECT_TYPE_BEZ': 'DBMS', 'CONSTANT': 'DssTypeDBMS',
             'DESCRIPTION': 'Holds information about a type of physical database (DBMS definition)'},
            {'OBJECT_TYPE_ID': '59', 'OBJECT_TYPE_BEZ': 'PromptAnswer', 'CONSTANT': 'DssTypePromptAnswer',
             'DESCRIPTION': 'Holds single prompt answer information'},
            {'OBJECT_TYPE_ID': '60', 'OBJECT_TYPE_BEZ': 'PromptAnswers', 'CONSTANT': 'DssTypePromptAnswers',
             'DESCRIPTION': 'Holds multiple prompt answer information'},
            {'OBJECT_TYPE_ID': '61', 'OBJECT_TYPE_BEZ': 'GraphStyle', 'CONSTANT': 'DssTypeGraphStyle',
             'DESCRIPTION': 'Holds grapth style information for report templates'},
            {'OBJECT_TYPE_ID': '62', 'OBJECT_TYPE_BEZ': 'ChangeJournalSearch', 'CONSTANT': 'DssTypeChangeJournalSearch',
             'DESCRIPTION': 'Holds information about Change Journal search objects'},
            {'OBJECT_TYPE_ID': '63', 'OBJECT_TYPE_BEZ': 'Blob', 'CONSTANT': 'DssTypeBlob',
             'DESCRIPTION': 'Holds information about Blob images'},
            {'OBJECT_TYPE_ID': '64', 'OBJECT_TYPE_BEZ': 'DashboardTemplate', 'CONSTANT': 'DssTypeDashboardTemplate',
             'DESCRIPTION': 'Describes templates used in dashboards'},
            {'OBJECT_TYPE_ID': '65', 'OBJECT_TYPE_BEZ': 'Flag', 'CONSTANT': 'DssTypeFlag',
             'DESCRIPTION': 'Used to flag certain objects. The flag itself doesn''t store the relationship, which is stored in link item instead'},
            {'OBJECT_TYPE_ID': '66', 'OBJECT_TYPE_BEZ': 'ChangeJournal', 'CONSTANT': 'DssTypeChangeJournal',
             'DESCRIPTION': 'Holds a list of Change Journal entries'},
            {'OBJECT_TYPE_ID': '67', 'OBJECT_TYPE_BEZ': 'ExternalShortcut', 'CONSTANT': 'DssTypeExternalShortcut',
             'DESCRIPTION': 'A shortcut object whose target is ExternalShortcutTarget (rather than regular object)'},
            {'OBJECT_TYPE_ID': '68', 'OBJECT_TYPE_BEZ': 'ExternalShortcutTarget',
             'CONSTANT': 'DssTypeExternalShortcutTarget',
             'DESCRIPTION': 'A transient object which is used to refer to external resource like web server file'},
            {'OBJECT_TYPE_ID': '69', 'OBJECT_TYPE_BEZ': 'Reconciliation', 'CONSTANT': 'DssTypeReconciliation',
             'DESCRIPTION': 'Identifies equivilent objects in two environments. Mainly used for dataset replacement.'},
            {'OBJECT_TYPE_ID': '70', 'OBJECT_TYPE_BEZ': 'Layer', 'CONSTANT': 'DssTypeLayer',
             'DESCRIPTION': 'Holds a collection of tables and attributes with their position info'},
            {'OBJECT_TYPE_ID': '71', 'OBJECT_TYPE_BEZ': 'Palette', 'CONSTANT': 'DssTypePalette',
             'DESCRIPTION': 'Holds a collection of colors'},
            {'OBJECT_TYPE_ID': '72', 'OBJECT_TYPE_BEZ': 'Thresholds', 'CONSTANT': 'DssTypeThresholds',
             'DESCRIPTION': 'Standalone thresholds object which holds a collection of tranditional thresholds structures'},
            {'OBJECT_TYPE_ID': '73', 'OBJECT_TYPE_BEZ': 'PersonalView', 'CONSTANT': 'DssTypePersonalView',
             'DESCRIPTION': 'Holds user''s manipulation on RWD and dashboard. (Personal View)'},
            {'OBJECT_TYPE_ID': '74', 'OBJECT_TYPE_BEZ': 'FeatureFlag', 'CONSTANT': 'DssTypeFeatureFlag',
             'DESCRIPTION': 'Holds the on/off/default state of a feature'}
        ]