-- Add ontology column
ALTER TABLE lu_brand ADD COLUMN ontology_bez VARCHAR(500);

ALTER TABLE lu_brand ADD COLUMN ontology_uri VARCHAR(500);

ALTER TABLE lu_brand ADD COLUMN ontology_url VARCHAR(500);

-- Populate ontology from Wikidata_Label
UPDATE lu_brand SET             ontology_id = 'Q229329'           , ontology_uri = 'https://www.wikidata.org/entity/Q229329'             WHERE Brand_ID = 201;
UPDATE lu_brand SET             ontology_id = 'Q277230'           , ontology_uri = 'https://www.wikidata.org/entity/Q277230'             WHERE Brand_ID = 401;
UPDATE lu_brand SET             ontology_id = 'Q7857'           , ontology_uri = 'https://www.wikidata.org/entity/Q7857'             WHERE Brand_ID = 301;
UPDATE lu_brand SET             ontology_id = 'Q27593'           , ontology_uri = 'https://www.wikidata.org/entity/Q27593'             WHERE Brand_ID = 403;
UPDATE lu_brand SET             ontology_id = 'Q302860'           , ontology_uri = 'https://www.wikidata.org/entity/Q302860'             WHERE Brand_ID = 402;
UPDATE lu_brand SET             ontology_id = 'Q151634'           , ontology_uri = 'https://www.wikidata.org/entity/Q151634'             WHERE Brand_ID = 404;
UPDATE lu_brand SET             ontology_id = 'Q132952'           , ontology_uri = 'https://www.wikidata.org/entity/Q132952'             WHERE Brand_ID = 302;
UPDATE lu_brand SET             ontology_id = 'Q313260'           , ontology_uri = 'https://www.wikidata.org/entity/Q313260'             WHERE Brand_ID = 405;
UPDATE lu_brand SET             ontology_id = 'Q1532260'           , ontology_uri = 'https://www.wikidata.org/entity/Q1532260'             WHERE Brand_ID = 101;
UPDATE lu_brand SET             ontology_id = 'Q81447'           , ontology_uri = 'https://www.wikidata.org/entity/Q81447'             WHERE Brand_ID = 102;
UPDATE lu_brand SET             ontology_id = 'Q484255'           , ontology_uri = 'https://www.wikidata.org/entity/Q484255'             WHERE Brand_ID = 406;
UPDATE lu_brand SET             ontology_id = 'Q371782'           , ontology_uri = 'https://www.wikidata.org/entity/Q371782'             WHERE Brand_ID = 407;
UPDATE lu_brand SET             ontology_id = 'Q138846'           , ontology_uri = 'https://www.wikidata.org/entity/Q138846'             WHERE Brand_ID = 103;
UPDATE lu_brand SET             ontology_id = 'Q460425'           , ontology_uri = 'https://www.wikidata.org/entity/Q460425'             WHERE Brand_ID = 104;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 105;
UPDATE lu_brand SET             ontology_id = 'Q534898'           , ontology_uri = 'https://www.wikidata.org/entity/Q534898'             WHERE Brand_ID = 303;
UPDATE lu_brand SET             ontology_id = 'Q193146'           , ontology_uri = 'https://www.wikidata.org/entity/Q193146'             WHERE Brand_ID = 304;
UPDATE lu_brand SET             ontology_id = 'Q41548'           , ontology_uri = 'https://www.wikidata.org/entity/Q41548'             WHERE Brand_ID = 305;
UPDATE lu_brand SET             ontology_id = 'Q1340'           , ontology_uri = 'https://www.wikidata.org/entity/Q1340'             WHERE Brand_ID = 408;
UPDATE lu_brand SET             ontology_id = 'Q125121'           , ontology_uri = 'https://www.wikidata.org/entity/Q125121'             WHERE Brand_ID = 409;
UPDATE lu_brand SET             ontology_id = 'Q132524'           , ontology_uri = 'https://www.wikidata.org/entity/Q132524'             WHERE Brand_ID = 106;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 108;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 107;
UPDATE lu_brand SET             ontology_id = 'Q371997'           , ontology_uri = 'https://www.wikidata.org/entity/Q371997'             WHERE Brand_ID = 410;
UPDATE lu_brand SET             ontology_id = 'Q213588'           , ontology_uri = 'https://www.wikidata.org/entity/Q213588'             WHERE Brand_ID = 306;
UPDATE lu_brand SET             ontology_id = 'Q705352'           , ontology_uri = 'https://www.wikidata.org/entity/Q705352'             WHERE Brand_ID = 307;
UPDATE lu_brand SET             ontology_id = 'Q213647'           , ontology_uri = 'https://www.wikidata.org/entity/Q213647'             WHERE Brand_ID = 412;
UPDATE lu_brand SET             ontology_id = 'Q34529'           , ontology_uri = 'https://www.wikidata.org/entity/Q34529'             WHERE Brand_ID = 308;
UPDATE lu_brand SET             ontology_id = 'Q213512'           , ontology_uri = 'https://www.wikidata.org/entity/Q213512'             WHERE Brand_ID = 414;
UPDATE lu_brand SET             ontology_id = 'Q55176561'           , ontology_uri = 'https://www.wikidata.org/entity/Q55176561'             WHERE Brand_ID = 109;
UPDATE lu_brand SET             ontology_id = 'Q863030'           , ontology_uri = 'https://www.wikidata.org/entity/Q863030'             WHERE Brand_ID = 309;
UPDATE lu_brand SET             ontology_id = 'Q880845'           , ontology_uri = 'https://www.wikidata.org/entity/Q880845'             WHERE Brand_ID = 415;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 110;
UPDATE lu_brand SET             ontology_id = 'Q1424655'           , ontology_uri = 'https://www.wikidata.org/entity/Q1424655'             WHERE Brand_ID = 310;
UPDATE lu_brand SET             ontology_id = 'Q886047'           , ontology_uri = 'https://www.wikidata.org/entity/Q886047'             WHERE Brand_ID = 416;
UPDATE lu_brand SET             ontology_id = 'Q234693'           , ontology_uri = 'https://www.wikidata.org/entity/Q234693'             WHERE Brand_ID = 417;
UPDATE lu_brand SET             ontology_id = 'Q203219'           , ontology_uri = 'https://www.wikidata.org/entity/Q203219'             WHERE Brand_ID = 311;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 111;
UPDATE lu_brand SET             ontology_id = 'Q115379690'           , ontology_uri = 'https://www.wikidata.org/entity/Q115379690'             WHERE Brand_ID = 112;
UPDATE lu_brand SET             ontology_id = 'Q690974'           , ontology_uri = 'https://www.wikidata.org/entity/Q690974'             WHERE Brand_ID = 418;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 113;
UPDATE lu_brand SET             ontology_id = 'Q2680'           , ontology_uri = 'https://www.wikidata.org/entity/Q2680'             WHERE Brand_ID = 312;
UPDATE lu_brand SET             ontology_id = 'Q432577'           , ontology_uri = 'https://www.wikidata.org/entity/Q432577'             WHERE Brand_ID = 419;
UPDATE lu_brand SET             ontology_id = 'Q1033047'           , ontology_uri = 'https://www.wikidata.org/entity/Q1033047'             WHERE Brand_ID = 420;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 114;
UPDATE lu_brand SET             ontology_id = 'Q311093'           , ontology_uri = 'https://www.wikidata.org/entity/Q311093'             WHERE Brand_ID = 313;
UPDATE lu_brand SET             ontology_id = 'Q138327'           , ontology_uri = 'https://www.wikidata.org/entity/Q138327'             WHERE Brand_ID = 314;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 115;
UPDATE lu_brand SET             ontology_id = 'Q59532961'           , ontology_uri = 'https://www.wikidata.org/entity/Q59532961'             WHERE Brand_ID = 116;
UPDATE lu_brand SET             ontology_id = 'Q310926'           , ontology_uri = 'https://www.wikidata.org/entity/Q310926'             WHERE Brand_ID = 315;
UPDATE lu_brand SET             ontology_id = 'Q3626188'           , ontology_uri = 'https://www.wikidata.org/entity/Q3626188'             WHERE Brand_ID = 316;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 317;
UPDATE lu_brand SET             ontology_id = 'Q71243'           , ontology_uri = 'https://www.wikidata.org/entity/Q71243'             WHERE Brand_ID = 318;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 421;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 117;
UPDATE lu_brand SET             ontology_id = 'Q593366'           , ontology_uri = 'https://www.wikidata.org/entity/Q593366'             WHERE Brand_ID = 422;
UPDATE lu_brand SET             ontology_id = 'Q1109596'           , ontology_uri = 'https://www.wikidata.org/entity/Q1109596'             WHERE Brand_ID = 423;
UPDATE lu_brand SET             ontology_id = 'Q18086612'           , ontology_uri = 'https://www.wikidata.org/entity/Q18086612'             WHERE Brand_ID = 118;
UPDATE lu_brand SET             ontology_id = 'Q351701'           , ontology_uri = 'https://www.wikidata.org/entity/Q351701'             WHERE Brand_ID = 119;
UPDATE lu_brand SET             ontology_id = 'Q673567'           , ontology_uri = 'https://www.wikidata.org/entity/Q673567'             WHERE Brand_ID = 120;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 121;
UPDATE lu_brand SET             ontology_id = 'Q607793'           , ontology_uri = 'https://www.wikidata.org/entity/Q607793'             WHERE Brand_ID = 319;
UPDATE lu_brand SET             ontology_id = 'Q832086'           , ontology_uri = 'https://www.wikidata.org/entity/Q832086'             WHERE Brand_ID = 424;
UPDATE lu_brand SET             ontology_id = 'Q294185'           , ontology_uri = 'https://www.wikidata.org/entity/Q294185'             WHERE Brand_ID = 320;
UPDATE lu_brand SET             ontology_id = 'Q1173663'           , ontology_uri = 'https://www.wikidata.org/entity/Q1173663'             WHERE Brand_ID = 321;
UPDATE lu_brand SET             ontology_id = 'Q5237560'           , ontology_uri = 'https://www.wikidata.org/entity/Q5237560'             WHERE Brand_ID = 122;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 123;
UPDATE lu_brand SET             ontology_id = 'Q1182355'           , ontology_uri = 'https://www.wikidata.org/entity/Q1182355'             WHERE Brand_ID = 425;
UPDATE lu_brand SET             ontology_id = 'Q318506'           , ontology_uri = 'https://www.wikidata.org/entity/Q318506'             WHERE Brand_ID = 124;
UPDATE lu_brand SET             ontology_id = 'Q200768'           , ontology_uri = 'https://www.wikidata.org/entity/Q200768'             WHERE Brand_ID = 322;
UPDATE lu_brand SET             ontology_id = 'Q43404'           , ontology_uri = 'https://www.wikidata.org/entity/Q43404'             WHERE Brand_ID = 323;
UPDATE lu_brand SET             ontology_id = 'Q7414'           , ontology_uri = 'https://www.wikidata.org/entity/Q7414'             WHERE Brand_ID = 426;
UPDATE lu_brand SET             ontology_id = 'Q316454'           , ontology_uri = 'https://www.wikidata.org/entity/Q316454'             WHERE Brand_ID = 427;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 428;
UPDATE lu_brand SET             ontology_id = 'Q120189107'           , ontology_uri = 'https://www.wikidata.org/entity/Q120189107'             WHERE Brand_ID = 125;
UPDATE lu_brand SET             ontology_id = 'Q676094'           , ontology_uri = 'https://www.wikidata.org/entity/Q676094'             WHERE Brand_ID = 324;
UPDATE lu_brand SET             ontology_id = 'Q713099'           , ontology_uri = 'https://www.wikidata.org/entity/Q713099'             WHERE Brand_ID = 429;
UPDATE lu_brand SET             ontology_id = 'Q43874'           , ontology_uri = 'https://www.wikidata.org/entity/Q43874'             WHERE Brand_ID = 325;
UPDATE lu_brand SET             ontology_id = 'Q721957'           , ontology_uri = 'https://www.wikidata.org/entity/Q721957'             WHERE Brand_ID = 326;
UPDATE lu_brand SET             ontology_id = 'Q1293908'           , ontology_uri = 'https://www.wikidata.org/entity/Q1293908'             WHERE Brand_ID = 126;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 127;
UPDATE lu_brand SET             ontology_id = 'Q211144'           , ontology_uri = 'https://www.wikidata.org/entity/Q211144'             WHERE Brand_ID = 327;
UPDATE lu_brand SET             ontology_id = 'Q168724'           , ontology_uri = 'https://www.wikidata.org/entity/Q168724'             WHERE Brand_ID = 328;
UPDATE lu_brand SET             ontology_id = 'Q38257'           , ontology_uri = 'https://www.wikidata.org/entity/Q38257'             WHERE Brand_ID = 430;
UPDATE lu_brand SET             ontology_id = 'Q380511'           , ontology_uri = 'https://www.wikidata.org/entity/Q380511'             WHERE Brand_ID = 128;
UPDATE lu_brand SET             ontology_id = 'Q23434'           , ontology_uri = 'https://www.wikidata.org/entity/Q23434'             WHERE Brand_ID = 129;
UPDATE lu_brand SET             ontology_id = 'Q223875'           , ontology_uri = 'https://www.wikidata.org/entity/Q223875'             WHERE Brand_ID = 431;
UPDATE lu_brand SET             ontology_id = 'Q217776'           , ontology_uri = 'https://www.wikidata.org/entity/Q217776'             WHERE Brand_ID = 329;
UPDATE lu_brand SET             ontology_id = 'Q484615'           , ontology_uri = 'https://www.wikidata.org/entity/Q484615'             WHERE Brand_ID = 330;
UPDATE lu_brand SET             ontology_id = 'Q93354'           , ontology_uri = 'https://www.wikidata.org/entity/Q93354'             WHERE Brand_ID = 130;
UPDATE lu_brand SET             ontology_id = 'Q464241'           , ontology_uri = 'https://www.wikidata.org/entity/Q464241'             WHERE Brand_ID = 432;
UPDATE lu_brand SET             ontology_id = 'Q2449557'           , ontology_uri = 'https://www.wikidata.org/entity/Q2449557'             WHERE Brand_ID = 433;
UPDATE lu_brand SET             ontology_id = 'Q8962681'           , ontology_uri = 'https://www.wikidata.org/entity/Q8962681'             WHERE Brand_ID = 131;
UPDATE lu_brand SET             ontology_id = 'Q5604'           , ontology_uri = 'https://www.wikidata.org/entity/Q5604'             WHERE Brand_ID = 132;
UPDATE lu_brand SET             ontology_id = 'Q576465'           , ontology_uri = 'https://www.wikidata.org/entity/Q576465'             WHERE Brand_ID = 202;
UPDATE lu_brand SET             ontology_id = 'Q216288'           , ontology_uri = 'https://www.wikidata.org/entity/Q216288'             WHERE Brand_ID = 434;
UPDATE lu_brand SET             ontology_id = 'Q64138528'           , ontology_uri = 'https://www.wikidata.org/entity/Q64138528'             WHERE Brand_ID = 133;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 134;
UPDATE lu_brand SET             ontology_id = 'Q3335'           , ontology_uri = 'https://www.wikidata.org/entity/Q3335'             WHERE Brand_ID = 135;
UPDATE lu_brand SET             ontology_id = 'Q366584'           , ontology_uri = 'https://www.wikidata.org/entity/Q366584'             WHERE Brand_ID = 435;
UPDATE lu_brand SET             ontology_id = 'Q7317'           , ontology_uri = 'https://www.wikidata.org/entity/Q7317'             WHERE Brand_ID = 436;
UPDATE lu_brand SET             ontology_id = 'Q730046'           , ontology_uri = 'https://www.wikidata.org/entity/Q730046'             WHERE Brand_ID = 437;
UPDATE lu_brand SET             ontology_id = 'Q47871'           , ontology_uri = 'https://www.wikidata.org/entity/Q47871'             WHERE Brand_ID = 438;
UPDATE lu_brand SET             ontology_id = 'Q108366'           , ontology_uri = 'https://www.wikidata.org/entity/Q108366'             WHERE Brand_ID = 331;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 136;
UPDATE lu_brand SET             ontology_id = 'Q1585599'           , ontology_uri = 'https://www.wikidata.org/entity/Q1585599'             WHERE Brand_ID = 203;
UPDATE lu_brand SET             ontology_id = 'Q182658'           , ontology_uri = 'https://www.wikidata.org/entity/Q182658'             WHERE Brand_ID = 137;
UPDATE lu_brand SET             ontology_id = 'Q238383'           , ontology_uri = 'https://www.wikidata.org/entity/Q238383'             WHERE Brand_ID = 332;
UPDATE lu_brand SET             ontology_id = 'Q225657'           , ontology_uri = 'https://www.wikidata.org/entity/Q225657'             WHERE Brand_ID = 333;
UPDATE lu_brand SET             ontology_id = 'Q5965492'           , ontology_uri = 'https://www.wikidata.org/entity/Q5965492'             WHERE Brand_ID = 138;
UPDATE lu_brand SET             ontology_id = 'Q80978'           , ontology_uri = 'https://www.wikidata.org/entity/Q80978'             WHERE Brand_ID = 204;
UPDATE lu_brand SET             ontology_id = 'Q53238'           , ontology_uri = 'https://www.wikidata.org/entity/Q53238'             WHERE Brand_ID = 205;
UPDATE lu_brand SET             ontology_id = 'Q1476499'           , ontology_uri = 'https://www.wikidata.org/entity/Q1476499'             WHERE Brand_ID = 439;
UPDATE lu_brand SET             ontology_id = 'Q16390'           , ontology_uri = 'https://www.wikidata.org/entity/Q16390'             WHERE Brand_ID = 334;
UPDATE lu_brand SET             ontology_id = 'Q330353'           , ontology_uri = 'https://www.wikidata.org/entity/Q330353'             WHERE Brand_ID = 335;
UPDATE lu_brand SET             ontology_id = 'Q125428932'           , ontology_uri = 'https://www.wikidata.org/entity/Q125428932'             WHERE Brand_ID = 139;
UPDATE lu_brand SET             ontology_id = 'Q639197'           , ontology_uri = 'https://www.wikidata.org/entity/Q639197'             WHERE Brand_ID = 440;
UPDATE lu_brand SET             ontology_id = 'Q79904'           , ontology_uri = 'https://www.wikidata.org/entity/Q79904'             WHERE Brand_ID = 140;
UPDATE lu_brand SET             ontology_id = 'Q39792'           , ontology_uri = 'https://www.wikidata.org/entity/Q39792'             WHERE Brand_ID = 336;
UPDATE lu_brand SET             ontology_id = 'Q9424'           , ontology_uri = 'https://www.wikidata.org/entity/Q9424'             WHERE Brand_ID = 337;
UPDATE lu_brand SET             ontology_id = 'Q299483'           , ontology_uri = 'https://www.wikidata.org/entity/Q299483'             WHERE Brand_ID = 338;
UPDATE lu_brand SET             ontology_id = 'Q973958'           , ontology_uri = 'https://www.wikidata.org/entity/Q973958'             WHERE Brand_ID = 141;
UPDATE lu_brand SET             ontology_id = 'Q213861'           , ontology_uri = 'https://www.wikidata.org/entity/Q213861'             WHERE Brand_ID = 142;
UPDATE lu_brand SET             ontology_id = 'Q6882'           , ontology_uri = 'https://www.wikidata.org/entity/Q6882'             WHERE Brand_ID = 143;
UPDATE lu_brand SET             ontology_id = 'Q202041'           , ontology_uri = 'https://www.wikidata.org/entity/Q202041'             WHERE Brand_ID = 441;
UPDATE lu_brand SET             ontology_id = 'Q131324'           , ontology_uri = 'https://www.wikidata.org/entity/Q131324'             WHERE Brand_ID = 442;
UPDATE lu_brand SET             ontology_id = 'Q361412'           , ontology_uri = 'https://www.wikidata.org/entity/Q361412'             WHERE Brand_ID = 339;
UPDATE lu_brand SET             ontology_id = 'Q32522'           , ontology_uri = 'https://www.wikidata.org/entity/Q32522'             WHERE Brand_ID = 340;
UPDATE lu_brand SET             ontology_id = 'Q175104'           , ontology_uri = 'https://www.wikidata.org/entity/Q175104'             WHERE Brand_ID = 341;
UPDATE lu_brand SET             ontology_id = 'Q40504'           , ontology_uri = 'https://www.wikidata.org/entity/Q40504'             WHERE Brand_ID = 342;
UPDATE lu_brand SET             ontology_id = 'Q106906762'           , ontology_uri = 'https://www.wikidata.org/entity/Q106906762'             WHERE Brand_ID = 144;
UPDATE lu_brand SET             ontology_id = 'Q4442402'           , ontology_uri = 'https://www.wikidata.org/entity/Q4442402'             WHERE Brand_ID = 443;
UPDATE lu_brand SET             ontology_id = 'Q1138602'           , ontology_uri = 'https://www.wikidata.org/entity/Q1138602'             WHERE Brand_ID = 343;
UPDATE lu_brand SET             ontology_id = 'Q20178'           , ontology_uri = 'https://www.wikidata.org/entity/Q20178'             WHERE Brand_ID = 344;
UPDATE lu_brand SET             ontology_id = 'Q382604'           , ontology_uri = 'https://www.wikidata.org/entity/Q382604'             WHERE Brand_ID = 145;
UPDATE lu_brand SET             ontology_id = 'Q131805'           , ontology_uri = 'https://www.wikidata.org/entity/Q131805'             WHERE Brand_ID = 146;
UPDATE lu_brand SET             ontology_id = 'Q112398662'           , ontology_uri = 'https://www.wikidata.org/entity/Q112398662'             WHERE Brand_ID = 147;
UPDATE lu_brand SET             ontology_id = 'Q80938'           , ontology_uri = 'https://www.wikidata.org/entity/Q80938'             WHERE Brand_ID = 345;
UPDATE lu_brand SET             ontology_id = 'Q6271024'           , ontology_uri = 'https://www.wikidata.org/entity/Q6271024'             WHERE Brand_ID = 148;
UPDATE lu_brand SET             ontology_id = 'Q120600768'           , ontology_uri = 'https://www.wikidata.org/entity/Q120600768'             WHERE Brand_ID = 149;
UPDATE lu_brand SET             ontology_id = 'Q104158481'           , ontology_uri = 'https://www.wikidata.org/entity/Q104158481'             WHERE Brand_ID = 150;
UPDATE lu_brand SET             ontology_id = 'Q99613387'           , ontology_uri = 'https://www.wikidata.org/entity/Q99613387'             WHERE Brand_ID = 151;
UPDATE lu_brand SET             ontology_id = 'Q40523'           , ontology_uri = 'https://www.wikidata.org/entity/Q40523'             WHERE Brand_ID = 346;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 152;
UPDATE lu_brand SET             ontology_id = 'Q202765'           , ontology_uri = 'https://www.wikidata.org/entity/Q202765'             WHERE Brand_ID = 347;
UPDATE lu_brand SET             ontology_id = 'Q1738056'           , ontology_uri = 'https://www.wikidata.org/entity/Q1738056'             WHERE Brand_ID = 348;
UPDATE lu_brand SET             ontology_id = 'Q2248393'           , ontology_uri = 'https://www.wikidata.org/entity/Q2248393'             WHERE Brand_ID = 444;
UPDATE lu_brand SET             ontology_id = 'Q25144'           , ontology_uri = 'https://www.wikidata.org/entity/Q25144'             WHERE Brand_ID = 349;
UPDATE lu_brand SET             ontology_id = 'Q76478'           , ontology_uri = 'https://www.wikidata.org/entity/Q76478'             WHERE Brand_ID = 350;
UPDATE lu_brand SET             ontology_id = 'Q6491283'           , ontology_uri = 'https://www.wikidata.org/entity/Q6491283'             WHERE Brand_ID = 181;
UPDATE lu_brand SET             ontology_id = 'Q2447661'           , ontology_uri = 'https://www.wikidata.org/entity/Q2447661'             WHERE Brand_ID = 445;
UPDATE lu_brand SET             ontology_id = 'Q38111'           , ontology_uri = 'https://www.wikidata.org/entity/Q38111'             WHERE Brand_ID = 351;
UPDATE lu_brand SET             ontology_id = 'Q58444'           , ontology_uri = 'https://www.wikidata.org/entity/Q58444'             WHERE Brand_ID = 352;
UPDATE lu_brand SET             ontology_id = 'Q483673'           , ontology_uri = 'https://www.wikidata.org/entity/Q483673'             WHERE Brand_ID = 446;
UPDATE lu_brand SET             ontology_id = 'Q237654'           , ontology_uri = 'https://www.wikidata.org/entity/Q237654'             WHERE Brand_ID = 447;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 153;
UPDATE lu_brand SET             ontology_id = 'Q255'           , ontology_uri = 'https://www.wikidata.org/entity/Q255'             WHERE Brand_ID = 448;
UPDATE lu_brand SET             ontology_id = 'Q111972824'           , ontology_uri = 'https://www.wikidata.org/entity/Q111972824'             WHERE Brand_ID = 154;
UPDATE lu_brand SET             ontology_id = 'Q1744'           , ontology_uri = 'https://www.wikidata.org/entity/Q1744'             WHERE Brand_ID = 449;
UPDATE lu_brand SET             ontology_id = 'Q6761524'           , ontology_uri = 'https://www.wikidata.org/entity/Q6761524'             WHERE Brand_ID = 155;
UPDATE lu_brand SET             ontology_id = 'Q41076'           , ontology_uri = 'https://www.wikidata.org/entity/Q41076'             WHERE Brand_ID = 450;
UPDATE lu_brand SET             ontology_id = 'Q112735591'           , ontology_uri = 'https://www.wikidata.org/entity/Q112735591'             WHERE Brand_ID = 156;
UPDATE lu_brand SET             ontology_id = 'Q34012'           , ontology_uri = 'https://www.wikidata.org/entity/Q34012'             WHERE Brand_ID = 353;
UPDATE lu_brand SET             ontology_id = 'Q28755'           , ontology_uri = 'https://www.wikidata.org/entity/Q28755'             WHERE Brand_ID = 354;
UPDATE lu_brand SET             ontology_id = 'Q315672'           , ontology_uri = 'https://www.wikidata.org/entity/Q315672'             WHERE Brand_ID = 451;
UPDATE lu_brand SET             ontology_id = 'Q229430'           , ontology_uri = 'https://www.wikidata.org/entity/Q229430'             WHERE Brand_ID = 452;
UPDATE lu_brand SET             ontology_id = 'Q356487'           , ontology_uri = 'https://www.wikidata.org/entity/Q356487'             WHERE Brand_ID = 453;
UPDATE lu_brand SET             ontology_id = 'Q42229'           , ontology_uri = 'https://www.wikidata.org/entity/Q42229'             WHERE Brand_ID = 355;
UPDATE lu_brand SET             ontology_id = 'Q270669'           , ontology_uri = 'https://www.wikidata.org/entity/Q270669'             WHERE Brand_ID = 454;
UPDATE lu_brand SET             ontology_id = 'Q238215'           , ontology_uri = 'https://www.wikidata.org/entity/Q238215'             WHERE Brand_ID = 455;
UPDATE lu_brand SET             ontology_id = 'Q202725'           , ontology_uri = 'https://www.wikidata.org/entity/Q202725'             WHERE Brand_ID = 356;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 157;
UPDATE lu_brand SET             ontology_id = 'Q172140'           , ontology_uri = 'https://www.wikidata.org/entity/Q172140'             WHERE Brand_ID = 357;
UPDATE lu_brand SET             ontology_id = 'Q2831'           , ontology_uri = 'https://www.wikidata.org/entity/Q2831'             WHERE Brand_ID = 456;
UPDATE lu_brand SET             ontology_id = 'Q104081'           , ontology_uri = 'https://www.wikidata.org/entity/Q104081'             WHERE Brand_ID = 358;
UPDATE lu_brand SET             ontology_id = 'Q2283'           , ontology_uri = 'https://www.wikidata.org/entity/Q2283'             WHERE Brand_ID = 206;
UPDATE lu_brand SET             ontology_id = 'Q39075737'           , ontology_uri = 'https://www.wikidata.org/entity/Q39075737'             WHERE Brand_ID = 359;
UPDATE lu_brand SET             ontology_id = 'Q185724'           , ontology_uri = 'https://www.wikidata.org/entity/Q185724'             WHERE Brand_ID = 360;
UPDATE lu_brand SET             ontology_id = 'Q354578'           , ontology_uri = 'https://www.wikidata.org/entity/Q354578'             WHERE Brand_ID = 207;
UPDATE lu_brand SET             ontology_id = 'Q16193751'           , ontology_uri = 'https://www.wikidata.org/entity/Q16193751'             WHERE Brand_ID = 158;
UPDATE lu_brand SET             ontology_id = 'Q239070'           , ontology_uri = 'https://www.wikidata.org/entity/Q239070'             WHERE Brand_ID = 457;
UPDATE lu_brand SET             ontology_id = 'Q130742'           , ontology_uri = 'https://www.wikidata.org/entity/Q130742'             WHERE Brand_ID = 458;
UPDATE lu_brand SET             ontology_id = 'Q550558'           , ontology_uri = 'https://www.wikidata.org/entity/Q550558'             WHERE Brand_ID = 361;
UPDATE lu_brand SET             ontology_id = 'Q109674306'           , ontology_uri = 'https://www.wikidata.org/entity/Q109674306'             WHERE Brand_ID = 159;
UPDATE lu_brand SET             ontology_id = 'Q173096'           , ontology_uri = 'https://www.wikidata.org/entity/Q173096'             WHERE Brand_ID = 160;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 161;
UPDATE lu_brand SET             ontology_id = 'Q683794'           , ontology_uri = 'https://www.wikidata.org/entity/Q683794'             WHERE Brand_ID = 208;
UPDATE lu_brand SET             ontology_id = 'Q1399'           , ontology_uri = 'https://www.wikidata.org/entity/Q1399'             WHERE Brand_ID = 162;
UPDATE lu_brand SET             ontology_id = 'Q42869'           , ontology_uri = 'https://www.wikidata.org/entity/Q42869'             WHERE Brand_ID = 362;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 163;
UPDATE lu_brand SET             ontology_id = 'Q382890'           , ontology_uri = 'https://www.wikidata.org/entity/Q382890'             WHERE Brand_ID = 459;
UPDATE lu_brand SET             ontology_id = 'Q688619'           , ontology_uri = 'https://www.wikidata.org/entity/Q688619'             WHERE Brand_ID = 209;
UPDATE lu_brand SET             ontology_id = 'Q124660621'           , ontology_uri = 'https://www.wikidata.org/entity/Q124660621'             WHERE Brand_ID = 460;
UPDATE lu_brand SET             ontology_id = 'Q133151'           , ontology_uri = 'https://www.wikidata.org/entity/Q133151'             WHERE Brand_ID = 461;
UPDATE lu_brand SET             ontology_id = 'Q674582'           , ontology_uri = 'https://www.wikidata.org/entity/Q674582'             WHERE Brand_ID = 212;
UPDATE lu_brand SET             ontology_id = 'Q53247'           , ontology_uri = 'https://www.wikidata.org/entity/Q53247'             WHERE Brand_ID = 210;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 363;
UPDATE lu_brand SET             ontology_id = 'Q436719'           , ontology_uri = 'https://www.wikidata.org/entity/Q436719'             WHERE Brand_ID = 364;
UPDATE lu_brand SET             ontology_id = 'Q41871'           , ontology_uri = 'https://www.wikidata.org/entity/Q41871'             WHERE Brand_ID = 365;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 164;
UPDATE lu_brand SET             ontology_id = 'Q117471840'           , ontology_uri = 'https://www.wikidata.org/entity/Q117471840'             WHERE Brand_ID = 366;
UPDATE lu_brand SET             ontology_id = 'Q2073250'           , ontology_uri = 'https://www.wikidata.org/entity/Q2073250'             WHERE Brand_ID = 165;
UPDATE lu_brand SET             ontology_id = 'Q2411171'           , ontology_uri = 'https://www.wikidata.org/entity/Q2411171'             WHERE Brand_ID = 211;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 462;
UPDATE lu_brand SET             ontology_id = 'Q218038'           , ontology_uri = 'https://www.wikidata.org/entity/Q218038'             WHERE Brand_ID = 213;
UPDATE lu_brand SET             ontology_id = 'Q117769611'           , ontology_uri = 'https://www.wikidata.org/entity/Q117769611'             WHERE Brand_ID = 166;
UPDATE lu_brand SET             ontology_id = 'Q1354212'           , ontology_uri = 'https://www.wikidata.org/entity/Q1354212'             WHERE Brand_ID = 167;
UPDATE lu_brand SET             ontology_id = 'Q390590'           , ontology_uri = 'https://www.wikidata.org/entity/Q390590'             WHERE Brand_ID = 463;
UPDATE lu_brand SET             ontology_id = 'Q41108'           , ontology_uri = 'https://www.wikidata.org/entity/Q41108'             WHERE Brand_ID = 464;
UPDATE lu_brand SET             ontology_id = 'Q10708'           , ontology_uri = 'https://www.wikidata.org/entity/Q10708'             WHERE Brand_ID = 465;
UPDATE lu_brand SET             ontology_id = 'Q2149111'           , ontology_uri = 'https://www.wikidata.org/entity/Q2149111'             WHERE Brand_ID = 367;
UPDATE lu_brand SET             ontology_id = 'Q539982'           , ontology_uri = 'https://www.wikidata.org/entity/Q539982'             WHERE Brand_ID = 168;
UPDATE lu_brand SET             ontology_id = 'Q207307'           , ontology_uri = 'https://www.wikidata.org/entity/Q207307'             WHERE Brand_ID = 368;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 169;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 170;
UPDATE lu_brand SET             ontology_id = 'Q7348995'           , ontology_uri = 'https://www.wikidata.org/entity/Q7348995'             WHERE Brand_ID = 369;
UPDATE lu_brand SET             ontology_id = 'Q59215'           , ontology_uri = 'https://www.wikidata.org/entity/Q59215'             WHERE Brand_ID = 370;
UPDATE lu_brand SET             ontology_id = 'Q83338'           , ontology_uri = 'https://www.wikidata.org/entity/Q83338'             WHERE Brand_ID = 371;
UPDATE lu_brand SET             ontology_id = 'Q7357112'           , ontology_uri = 'https://www.wikidata.org/entity/Q7357112'             WHERE Brand_ID = 372;
UPDATE lu_brand SET             ontology_id = 'Q11036'           , ontology_uri = 'https://www.wikidata.org/entity/Q11036'             WHERE Brand_ID = 466;
UPDATE lu_brand SET             ontology_id = 'Q40791'           , ontology_uri = 'https://www.wikidata.org/entity/Q40791'             WHERE Brand_ID = 373;
UPDATE lu_brand SET             ontology_id = 'Q1738801'           , ontology_uri = 'https://www.wikidata.org/entity/Q1738801'             WHERE Brand_ID = 467;
UPDATE lu_brand SET             ontology_id = 'Q457923'           , ontology_uri = 'https://www.wikidata.org/entity/Q457923'             WHERE Brand_ID = 171;
UPDATE lu_brand SET             ontology_id = 'Q218091'           , ontology_uri = 'https://www.wikidata.org/entity/Q218091'             WHERE Brand_ID = 468;
UPDATE lu_brand SET             ontology_id = 'Q1233327'           , ontology_uri = 'https://www.wikidata.org/entity/Q1233327'             WHERE Brand_ID = 374;
UPDATE lu_brand SET             ontology_id = 'Q364131'           , ontology_uri = 'https://www.wikidata.org/entity/Q364131'             WHERE Brand_ID = 469;
UPDATE lu_brand SET             ontology_id = 'Q190643'           , ontology_uri = 'https://www.wikidata.org/entity/Q190643'             WHERE Brand_ID = 214;
UPDATE lu_brand SET             ontology_id = 'Q339430'           , ontology_uri = 'https://www.wikidata.org/entity/Q339430'             WHERE Brand_ID = 470;
UPDATE lu_brand SET             ontology_id = 'Q184217'           , ontology_uri = 'https://www.wikidata.org/entity/Q184217'             WHERE Brand_ID = 471;
UPDATE lu_brand SET             ontology_id = 'Q41187'           , ontology_uri = 'https://www.wikidata.org/entity/Q41187'             WHERE Brand_ID = 215;
UPDATE lu_brand SET             ontology_id = 'Q292092'           , ontology_uri = 'https://www.wikidata.org/entity/Q292092'             WHERE Brand_ID = 472;
UPDATE lu_brand SET             ontology_id = 'Q768807'           , ontology_uri = 'https://www.wikidata.org/entity/Q768807'             WHERE Brand_ID = 473;
UPDATE lu_brand SET             ontology_id = 'Q21475355'           , ontology_uri = 'https://www.wikidata.org/entity/Q21475355'             WHERE Brand_ID = 474;
UPDATE lu_brand SET             ontology_id = 'Q114330365'           , ontology_uri = 'https://www.wikidata.org/entity/Q114330365'             WHERE Brand_ID = 172;
UPDATE lu_brand SET             ontology_id = 'Q2344550'           , ontology_uri = 'https://www.wikidata.org/entity/Q2344550'             WHERE Brand_ID = 173;
UPDATE lu_brand SET             ontology_id = 'Q116672586'           , ontology_uri = 'https://www.wikidata.org/entity/Q116672586'             WHERE Brand_ID = 174;
UPDATE lu_brand SET             ontology_id = 'Q725507'           , ontology_uri = 'https://www.wikidata.org/entity/Q725507'             WHERE Brand_ID = 375;
UPDATE lu_brand SET             ontology_id = 'Q706475'           , ontology_uri = 'https://www.wikidata.org/entity/Q706475'             WHERE Brand_ID = 376;
UPDATE lu_brand SET             ontology_id = 'Q714'           , ontology_uri = 'https://www.wikidata.org/entity/Q714'             WHERE Brand_ID = 475;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 175;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 176;
UPDATE lu_brand SET             ontology_id = 'Q465633'           , ontology_uri = 'https://www.wikidata.org/entity/Q465633'             WHERE Brand_ID = 377;
UPDATE lu_brand SET             ontology_id = 'Q152066'           , ontology_uri = 'https://www.wikidata.org/entity/Q152066'             WHERE Brand_ID = 476;
UPDATE lu_brand SET             ontology_id = 'Q1299'           , ontology_uri = 'https://www.wikidata.org/entity/Q1299'             WHERE Brand_ID = 413;
UPDATE lu_brand SET             ontology_id = 'Q189635'           , ontology_uri = 'https://www.wikidata.org/entity/Q189635'             WHERE Brand_ID = 477;
UPDATE lu_brand SET             ontology_id = 'Q151403'           , ontology_uri = 'https://www.wikidata.org/entity/Q151403'             WHERE Brand_ID = 177;
UPDATE lu_brand SET             ontology_id = 'Q29344'           , ontology_uri = 'https://www.wikidata.org/entity/Q29344'             WHERE Brand_ID = 178;
UPDATE lu_brand SET             ontology_id = 'Q3525467'           , ontology_uri = 'https://www.wikidata.org/entity/Q3525467'             WHERE Brand_ID = 179;
UPDATE lu_brand SET             ontology_id = 'Q131814'           , ontology_uri = 'https://www.wikidata.org/entity/Q131814'             WHERE Brand_ID = 478;
UPDATE lu_brand SET             ontology_id = 'Q742804'           , ontology_uri = 'https://www.wikidata.org/entity/Q742804'             WHERE Brand_ID = 479;
UPDATE lu_brand SET             ontology_id = 'Q37079'           , ontology_uri = 'https://www.wikidata.org/entity/Q37079'             WHERE Brand_ID = 378;
UPDATE lu_brand SET             ontology_id = 'Q2263'           , ontology_uri = 'https://www.wikidata.org/entity/Q2263'             WHERE Brand_ID = 379;
UPDATE lu_brand SET             ontology_id = 'Q216195'           , ontology_uri = 'https://www.wikidata.org/entity/Q216195'             WHERE Brand_ID = 180;
UPDATE lu_brand SET             ontology_id = 'Q187814'           , ontology_uri = 'https://www.wikidata.org/entity/Q187814'             WHERE Brand_ID = 480;
UPDATE lu_brand SET             ontology_id = 'Q131433'           , ontology_uri = 'https://www.wikidata.org/entity/Q131433'             WHERE Brand_ID = 481;
UPDATE lu_brand SET             ontology_id = 'Q3108914'           , ontology_uri = 'https://www.wikidata.org/entity/Q3108914'             WHERE Brand_ID = 482;
UPDATE lu_brand SET             ontology_id = 'Q215561'           , ontology_uri = 'https://www.wikidata.org/entity/Q215561'             WHERE Brand_ID = 483;
UPDATE lu_brand SET             ontology_id = 'Q107730'           , ontology_uri = 'https://www.wikidata.org/entity/Q107730'             WHERE Brand_ID = 380;
UPDATE lu_brand SET             ontology_id = 'Q132964'           , ontology_uri = 'https://www.wikidata.org/entity/Q132964'             WHERE Brand_ID = 182;
UPDATE lu_brand SET             ontology_id = 'Q736254'           , ontology_uri = 'https://www.wikidata.org/entity/Q736254'             WHERE Brand_ID = 484;
UPDATE lu_brand SET             ontology_id = 'Q7976619'           , ontology_uri = 'https://www.wikidata.org/entity/Q7976619'             WHERE Brand_ID = 381;
UPDATE lu_brand SET             ontology_id = 'Q8349'           , ontology_uri = 'https://www.wikidata.org/entity/Q8349'             WHERE Brand_ID = 485;
UPDATE lu_brand SET             ontology_id = 'Q110722652'           , ontology_uri = 'https://www.wikidata.org/entity/Q110722652'             WHERE Brand_ID = 382;
UPDATE lu_brand SET             ontology_id = 'Q740623'           , ontology_uri = 'https://www.wikidata.org/entity/Q740623'             WHERE Brand_ID = 486;
UPDATE lu_brand SET             ontology_id = 'Q112546767'           , ontology_uri = 'https://www.wikidata.org/entity/Q112546767'             WHERE Brand_ID = 487;
UPDATE lu_brand SET             ontology_id = 'Q34389'           , ontology_uri = 'https://www.wikidata.org/entity/Q34389'             WHERE Brand_ID = 488;
UPDATE lu_brand SET             ontology_id = 'Q40096'           , ontology_uri = 'https://www.wikidata.org/entity/Q40096'             WHERE Brand_ID = 489;
UPDATE lu_brand SET             ontology_id = 'Q1742896'           , ontology_uri = 'https://www.wikidata.org/entity/Q1742896'             WHERE Brand_ID = 183;
UPDATE lu_brand SET             ontology_id = 'Q44183'           , ontology_uri = 'https://www.wikidata.org/entity/Q44183'             WHERE Brand_ID = 184;
UPDATE lu_brand SET             ontology_id = 'Q311892'           , ontology_uri = 'https://www.wikidata.org/entity/Q311892'             WHERE Brand_ID = 383;
UPDATE lu_brand SET             ontology_id = 'Q188574'           , ontology_uri = 'https://www.wikidata.org/entity/Q188574'             WHERE Brand_ID = 490;
UPDATE lu_brand SET             ontology_id = 'Q25089'           , ontology_uri = 'https://www.wikidata.org/entity/Q25089'             WHERE Brand_ID = 185;
UPDATE lu_brand SET             ontology_id = 'Q152433'           , ontology_uri = 'https://www.wikidata.org/entity/Q152433'             WHERE Brand_ID = 216;
UPDATE lu_brand SET             ontology_id = 'No Ontology available'           , ontology_uri = 'No_ontology'             WHERE Brand_ID = 186;