conn_params:
  username: yourlogis
  password: your_password
  base_url: yourserver:yourPort/MicroStrategyLibrary/api
  project_id: B7CA92F04B9FAE8D941C3E9B7E0CD754
mstr_projects:
  pa_project_id: 7576CD5F48607C21C914ACBE053B259B
