"""Tool group *specific analysis*: natural-language BI question answering.

Ported from the former standalone mstr_collab_perplex_server. Runs the full
keyword-extraction → Perplexity RAG → prompt-answering → report-execution
pipeline and returns the result as CSV plus a browser link.

Importing this module loads the four RAG cubes into DataFrames (same loading
logic as notebooks/jup_chat_answer_prompt_page.ipynb) and builds the
flash-text keyword index — i.e. it happens once when the MCP server process
starts. Every query_bi_report call afterwards is served from the in-memory
copies and reuses the shared session-managed connection (_server_config).
"""

import contextlib
import json
import sys

import yaml

from mstr_robotics._paths import CONFIG_DIR
from mstr_robotics.mcp_servers._server_config import get_conn, get_report_url
from mstr_robotics.navigation import AnswerPrompts, MstrObjects
from mstr_robotics.report import Cube
from mstr_robotics.report import Rep as MstrRep
from mstr_robotics.user_rag import KeywordProcessor, Perplexity

# ---------------------------------------------------------------------------
# Static configuration
# ---------------------------------------------------------------------------

with open(CONFIG_DIR / "jupyter_objects_d.yml", "r") as fh:
    _jup_obj_d = yaml.safe_load(fh)

_rag_d = _jup_obj_d["turtorial_RAG"]  # RAG cube GUIDs
_colab_d = _jup_obj_d["jup_Colab_perplex"]  # template report / target folder

TEMPLATE_REP_ID = _colab_d["reports"]["report_id"]
AI_REP_FOLDER = _colab_d["folders"]["AI_genRep_folder_id"]
AI_REP_NAME = "dyn_prompt_page_botstat"

# ---------------------------------------------------------------------------
# One-time initialisation (runs when the server process starts)
# ---------------------------------------------------------------------------


def _load_rag_state():
    """Load the four RAG cubes into DataFrames and build the keyword index.

    Same loading logic as jup_chat_answer_prompt_page.ipynb: the DataFrames
    come straight from the RAG cubes generated by load_rag_cubes.ipynb
    (previously read from CSV files in the MCP_DATA folder).
    """
    conn = get_conn()
    i_cube = Cube()

    attribute_form_elements_df = i_cube.load_cube_to_df(conn=conn, cube_id=_rag_d["cube_attribute_form_elements_id"])
    attribute_elements_df = i_cube.load_cube_to_df(conn=conn, cube_id=_rag_d["cube_attribute_elements_id"])
    att_form_def_df = i_cube.load_cube_to_df(conn=conn, cube_id=_rag_d["cube_att_form_def_id"])
    obj_prp_rel_df = i_cube.load_cube_to_df(conn=conn, cube_id=_rag_d["cube_obj_prp_rel_id"])

    answer_prpts = AnswerPrompts(
        attribute_form_elements_df=attribute_form_elements_df,
        attribute_elements_df=attribute_elements_df,
        obj_prp_rel_df=obj_prp_rel_df,
        att_form_def_df=att_form_def_df,
    )

    # Keyword index – attributes and metrics
    bi_obj_df = obj_prp_rel_df[["object_name", "obj_type", "object_id"]][
        obj_prp_rel_df["obj_type"].isin(["attribute", "metric"])
    ]

    # tool agnostic definitions. Only MSTR for the moment
    element_df_d_l = [
        {
            "df": attribute_form_elements_df,
            "key_col": "element_val",
            "key_type": "element_val",
            "rag_cols": ["attribute_name", "form_name", "element_val"],
        },
        {
            "df": attribute_elements_df,
            "key_col": "element_val",
            "key_type": "element_val",
            "rag_cols": ["attribute_name", "element_val"],
        },
    ]
    obj_df_d_l = [
        {
            "df": bi_obj_df,
            "key_col": "object_name",
            "key_type": "object_name",
            "rag_cols": ["object_name", "obj_type"],
        }
    ]

    # Pre-load all known keywords into the flash-text processor (the
    # "vector store" handed to AnswerPrompts.AI_mstr_prp_page_ans)
    keyword_proc = KeywordProcessor()
    all_keywords = (
        list(attribute_form_elements_df["element_val"].dropna().unique())
        + list(attribute_elements_df["element_val"].dropna().unique())
        + list(bi_obj_df["object_name"].dropna().unique())
    )
    keyword_proc.load_keyword_processor(all_keywords)

    return answer_prpts, keyword_proc, element_df_d_l, obj_df_d_l


# stdout → stderr during MSTR access so connection banners and cube-loading
# progress never pollute the MCP stdio protocol (pure JSON on stdout).
with contextlib.redirect_stdout(sys.stderr):
    _answer_prpts, _keyword_proc, _element_df_d_l, _obj_df_d_l = _load_rag_state()

_perplexity = Perplexity()
_mstr_objects = MstrObjects()

# ---------------------------------------------------------------------------
# MCP tool
# ---------------------------------------------------------------------------


def query_bi_report(question: str) -> str:
    """Answer a natural-language BI question against MicroStrategy.

    The tool:
    1. Extracts keywords from the question using flash-text.
    2. Builds a RAG context from the pre-loaded RAG cubes (attributes,
       metrics, elements).
    3. Calls the Perplexity LLM (sonar-pro) to parse the question into a
       structured BI request (attributes, metrics, filters).
    4. Translates the request into MicroStrategy prompt answers.
    5. Saves a new report instance and executes it.
    6. Returns the result as CSV plus a browser link.

    Args:
        question: Natural-language BI request, e.g.
            "Show me Revenue and Profit for Year and Category,
             filter Year In 2022, 2023 and Category starts with B"
    """
    with contextlib.redirect_stdout(sys.stderr):
        return _answer_bi_question(question)


def _answer_bi_question(question: str) -> str:
    # --- Step 1: keyword extraction + RAG context ---------------------------
    key_word_l = _keyword_proc.extract_keywords(msg_t=question)

    att_elem_str = _mstr_objects.get_att_elem_str(_element_df_d_l, key_word_l=key_word_l)
    bi_obj_str = _mstr_objects.get_att_elem_str(_obj_df_d_l, key_word_l=key_word_l)

    sys_cont = _perplexity.rag_sys_cont(
        key_word_l=key_word_l,
        att_elem_str=att_elem_str,
        bi_obj_str=bi_obj_str,
    )

    # --- Step 2: LLM call + parse -------------------------------------------
    message_check_d = {"msg_nr": "1", "msg_t": question}
    message_check_d = _perplexity.call_perplexity(
        msg_t=question,
        sys_cont=sys_cont,
        message_check_d=message_check_d,
        temperature=0.1,
    )

    if message_check_d.get("valid_d_fg") != 1:
        err = message_check_d.get("err", "unknown error")
        return f"ERROR – Perplexity call failed: {err}"

    bi_request_d = _perplexity.parse_and_structure([message_check_d])

    # If the LLM has a clarifying question, surface it
    if bi_request_d.get("question"):
        return f"Clarification needed: {bi_request_d['question']}"

    # --- Step 3: build MicroStrategy prompt answers -------------------------
    try:
        conn = get_conn()
    except Exception as e:
        return f"ERROR – could not connect to MicroStrategy: {e}"

    try:
        prompt_answ = _answer_prpts.AI_mstr_prp_page_ans(
            conn=conn,
            vector_store=_keyword_proc,
            bi_request_d=bi_request_d,
            rep_dos_id=TEMPLATE_REP_ID,
        )
    except Exception as e:
        return f"ERROR – building prompt answers: {e}"

    # --- Step 4: save + execute report --------------------------------------
    try:
        rep_resp = _answer_prpts.save_AI_rep(
            conn=conn,
            report_id=TEMPLATE_REP_ID,
            prompt_answ=prompt_answ,
            ai_rep_name=AI_REP_NAME,
            ai_rep_folder_id=AI_REP_FOLDER,
        )
        new_rep_id = rep_resp.json()["id"]
    except Exception as e:
        return f"ERROR – saving report instance: {e}"

    try:
        i_rep = MstrRep()
        instance_id = i_rep.open_Instance(conn=conn, report_id=new_rep_id)
        df = i_rep.report_df(conn=conn, report_id=new_rep_id, instance_id=instance_id)
    except Exception as e:
        return f"ERROR – executing report {new_rep_id}: {e}"

    if df is None or df.empty:
        return f"Report executed but returned no data. Report ID: {new_rep_id}"

    # --- Step 5: return result ----------------------------------------------
    rows, cols = df.shape
    prp_rep_id=_answer_prpts.save_AI_rep(conn=conn,report_id=TEMPLATE_REP_ID
                                  ,prompt_answ=prompt_answ
                                  ,ai_rep_name=AI_REP_NAME
                                  ,promptOption ="filterAndTemplate"
                                  ,ai_rep_folder_id=AI_REP_FOLDER)
    prp_rep_id=prp_rep_id.json()["id"]
    url=i_rep.web_base_url(conn=conn,report_id=prp_rep_id)

    csv_text = df.to_csv(index=False)

    return (
        f"BI Request parsed:\n"
        f"  Attributes : {bi_request_d.get('attributes', [])}\n"
        f"  Metrics    : {bi_request_d.get('metrics', [])}\n"
        f"  Filters    : {json.dumps(bi_request_d.get('filter', {}), default=str)}\n\n"
        f"Report '{AI_REP_NAME}' — {rows} rows × {cols} columns\n"
        f"Open in MSTR: {url}\n\n"
        f"{csv_text}"
    )
